spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEYVAULT_ENDPOINT} # environment variable
      storage:
        blob:
          account-name: ${AZURE_STORAGE_ACCOUNT_NAME}

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  datasource:
    url: ${datasource.url} # secret from Azure Key Vault
    username: ${datasource.username} # secret from Azure Key Vault
    password: ${datasource.password} # secret from Azure Key Vault
  jpa:
    hibernate:
      ddl-auto: none # Turn off automatic DDL generation
  data:
    redis:
      host: ${redis-host} # secret from Azure Key Vault
      port: 6380
      ssl:
        enabled: true
      azure:
        passwordless-enabled: true
      password: ${redis-access-key}   # secret from Azure Key Vault
ai:
  openai:
    endpoint: ${AI_OPENAI_ENDPOINT:https://api.openai.com/v1/chat/completions} # environment variable with a default value
    api-key: ${ai-openai-api-key:your-openai-api-key} # secret from Azure Key Vault